language: php

php:
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=2.3.*
    - php: 7.1
      env: SYMFONY_VERSION=2.5.*
    - php: 7.1
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION='dev-master as 3.4'
  allow_failures:
    - php: hhvm

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; else composer require "symfony/symfony:dev-master" --no-update; fi;
  - if [ "$SYMFONY_VERSION" = "dev-master as 3.4" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
  - composer update --dev --prefer-source

script: phpunit

notifications:
  email:
    - travis-ci@composieux.fr

